SET HEADING OFF
SET FEEDBACK OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET TRIMSPOOL ON
SELECT 'TEAM_PRIV|SYSTEM|' || privilege
  FROM SESSION_PRIVS
 ORDER BY privilege;
SELECT 'TEAM_PRIV|ROLE|' || role
  FROM SESSION_ROLES
 ORDER BY role;
SELECT 'TEAM_PRIV|OBJECT|' || privilege || '|' || NVL(type, 'UNKNOWN')
  FROM ALL_TAB_PRIVS_RECD
 ORDER BY privilege, type;
SELECT 'TEAM_PRIV|COLUMN|' || privilege
  FROM ALL_COL_PRIVS_RECD
 ORDER BY privilege;
SELECT 'TEAM_PRIV|OWNED|' || object_type
  FROM USER_OBJECTS
 WHERE object_type <> 'SYNONYM'
 ORDER BY object_type;
