"""Generators for ORDS export fixtures, shared by the verifier tests and the fake SQLcl.

They build, from the structure real SQLcl/ORDS output has (generator header,
BEGIN, ENABLE_SCHEMA, DEFINE_* calls, COMMIT; END;), an export script, the
inventory lines ords_inventory.sql prints, and a whole SQLcl transcript. No
database or historical export is involved.
"""

SCHEMA = "REST_API"
SPOOL = ".sqlcl-schema-UkVTVF9BUEk"
DATE_LINE = "-- Schema: REST_API  Date: Tue Sep 01 04:30:31 2026 "

COUNTS = {"modules": 1, "templates": 2, "handlers": 3, "parameters": 1, "roles": 1, "privileges": 1, "enabled_objects": 0}


def export_text(schema: str = SCHEMA, counts: dict[str, int] | None = None, newline: str = "\n", handler_source: str = "null;") -> str:
    counts = {**COUNTS, **(counts or {})}
    lines = [
        "",
        "-- Generated by ORDS REST Data Services 26.2.3.r2371104",
        f"-- Schema: {schema}  Date: Tue Sep 01 04:30:31 2026 ",
        "--",
        "",
        "DECLARE",
        "",
        "  l_roles     OWA.VC_ARR;",
        "  l_modules   OWA.VC_ARR;",
        "  l_patterns  OWA.VC_ARR;",
        "",
        "BEGIN",
        f"  ORDS.ENABLE_SCHEMA(p_enabled => TRUE, p_schema => '{schema}', p_url_mapping_pattern => 'api');",
    ]
    for call, key in (
        ("DEFINE_MODULE", "modules"),
        ("DEFINE_TEMPLATE", "templates"),
        ("DEFINE_HANDLER", "handlers"),
        ("DEFINE_PARAMETER", "parameters"),
        ("CREATE_ROLE", "roles"),
        ("DEFINE_PRIVILEGE", "privileges"),
        ("ENABLE_OBJECT", "enabled_objects"),
    ):
        for number in range(counts[key]):
            lines += [
                f"  ORDS.{call}(",
                f"      p_name => 'item{number}',",
                f"      p_source => 'BEGIN {handler_source} END;');",
                "",
            ]
    lines += [
        "  ORDS.FINALIZE_IMPORT(", "      p_prune => FALSE,", "      p_objects => null);", "",
        "COMMIT;", "EXCEPTION", "  WHEN OTHERS THEN", "    ROLLBACK;", "    RAISE;", "", "END;", "",
    ]
    return newline.join(lines)


def inventory(label: str, **overrides: int) -> str:
    values = {
        "schemas": 1, "enabled": 1, "modules": 1, "templates": 2, "handlers": 3, "parameters": 1, "roles": 1,
        "privileges": 1, "privilege_roles": 1, "privilege_modules": 0, "privilege_mappings": 2,
        "enabled_objects": 0, "clients": 0,
    }
    values.update(overrides)
    return f"ORDS_INVENTORY:{label}:" + ",".join(f"{key}={value}" for key, value in values.items())


def transcript(user: str = SCHEMA, schema: str = SCHEMA, mode: str = "run", before: str | None = None, after: str | None = None, extra: str = "") -> str:
    lines = [
        f"SQLcl target: session_user={user}, current_schema={schema}, db_name=DEV, db_unique_name=DEV, service=dev",
        "ORDS version: 24.2.2.r1871943",
        f"ORDS_ACCESS_VERIFIED:{schema}",
        before if before is not None else inventory("before"),
        f"ORDS_EXPORT_MODE:{mode}",
        extra,
        after if after is not None else inventory("after"),
        f"ORDS_EXPORT_COMPLETE:{schema}",
    ]
    return "\n".join(line for line in lines if line) + "\n"
