"""scripts/ords_export.py: the evidence an ORDS export must carry before it is trusted.

The fixtures are generated here from the structure real SQLcl/ORDS output has
(generator header, BEGIN, ENABLE_SCHEMA, DEFINE_* calls, COMMIT; END;); no
database or historical export is involved.
"""

import contextlib
import io
import tempfile
import unittest
from pathlib import Path

from ords_fixtures import COUNTS, DATE_LINE, SCHEMA, SPOOL, export_text, inventory, transcript
from scripts import ords_export
from scripts.ords_export import OrdsExportError


class Fixture:
    def __init__(self, root: Path) -> None:
        self.root = root
        (root / "database" / SPOOL / "ords").mkdir(parents=True)
        (root / "verify" / SPOOL).mkdir(parents=True)
        self.transcript = root / "transcript.txt"

    @property
    def export(self) -> Path:
        return self.root / "database" / SPOOL / "ords" / "schema.sql"

    @property
    def second(self) -> Path:
        return self.root / "verify" / SPOOL / "schema.sql"

    def write(self, transcript_text: str, first: str | None = None, second: str | None = None) -> "Fixture":
        self.transcript.write_text(transcript_text, encoding="utf-8", newline="")
        # A successful verify removes the second export's folder: a test may verify twice.
        self.export.parent.mkdir(parents=True, exist_ok=True)
        self.second.parent.mkdir(parents=True, exist_ok=True)
        if first is not None:
            self.export.write_text(first, encoding="utf-8", newline="")
        if second is not None:
            self.second.write_text(second, encoding="utf-8", newline="")
        return self

    def verify(self, schema: str = SCHEMA, expected_user: str = SCHEMA) -> str:
        return ords_export.verify(self.root, SPOOL, schema, expected_user, self.transcript)


class OrdsExportVerificationTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.fixture = Fixture(Path(self.temporary.name))

    def good(self, **kwargs) -> Fixture:
        text = export_text(**kwargs)
        return self.fixture.write(transcript(), text, text)

    def assert_refused(self, fragment: str) -> None:
        with self.assertRaises(OrdsExportError) as raised:
            self.fixture.verify()
        self.assertIn(fragment, str(raised.exception))

    def test_a_complete_export_is_installed_without_its_timestamp_and_with_lf_endings(self) -> None:
        text = export_text(newline="\r\n")
        self.fixture.write(transcript(), text, text)
        summary = self.fixture.verify()
        installed = self.fixture.export.read_bytes()
        self.assertNotIn(b"\r", installed)
        self.assertNotIn(b"Date:", installed)
        self.assertTrue(installed.startswith(b"-- Generated by ORDS REST Data Services 26.2.3.r2371104\n-- Schema: REST_API\n--\n"))
        self.assertTrue(installed.endswith(b"COMMIT;\nEXCEPTION\n  WHEN OTHERS THEN\n    ROLLBACK;\n    RAISE;\n\nEND;\n"))
        self.assertFalse(self.fixture.second.exists(), "the second export must not stay in the staged mirror")
        self.assertIn("modules=1", summary)
        self.assertIn("handlers=3", summary)

    def test_two_exports_with_different_timestamps_are_equal(self) -> None:
        first = export_text()
        second = first.replace("04:30:31", "04:30:32")
        self.fixture.write(transcript(), first, second)
        self.fixture.verify()

    def test_a_rest_enabled_schema_without_metadata_is_a_verified_empty_result(self) -> None:
        empty = {key: 0 for key in COUNTS}
        text = export_text(counts=empty)
        before = inventory("before", modules=0, templates=0, handlers=0, parameters=0, roles=0, privileges=0, privilege_roles=0, privilege_mappings=0)
        after = before.replace(":before:", ":after:")
        self.fixture.write(transcript(before=before, after=after), text, text)
        self.assertIn("verified empty", self.fixture.verify())
        self.assertIn("ORDS.ENABLE_SCHEMA", self.fixture.export.read_text(encoding="utf-8"))

    def test_a_schema_that_is_not_rest_enabled_and_has_no_metadata_is_verified_empty(self) -> None:
        zero = inventory("before", schemas=0, enabled=0, modules=0, templates=0, handlers=0, parameters=0, roles=0,
                         privileges=0, privilege_roles=0, privilege_mappings=0)
        self.fixture.write(transcript(mode="skipped-not-enabled", before=zero, after=zero.replace(":before:", ":after:")))
        summary = self.fixture.verify()
        self.assertIn("verified empty", summary)
        installed = self.fixture.export.read_text(encoding="utf-8")
        self.assertIn("Verified empty", installed)
        self.assertTrue(installed.endswith("\n"))

    def test_not_rest_enabled_with_listed_metadata_is_an_inconsistent_inventory_not_empty(self) -> None:
        inconsistent = inventory("before", enabled=0)
        self.fixture.write(transcript(mode="skipped-not-enabled", before=inconsistent, after=inconsistent.replace(":before:", ":after:")))
        self.assert_refused("inventory is inconsistent")
        self.assertFalse(self.fixture.export.exists())

    def test_the_session_must_be_the_rest_schema_owner(self) -> None:
        text = export_text()
        self.fixture.write(transcript(user="DEPLOYER"), text, text)
        self.assert_refused("not the REST schema owner REST_API")

    def test_a_transcript_without_an_identity_is_refused(self) -> None:
        text = export_text()
        body = "\n".join(line for line in transcript().splitlines() if not line.startswith("SQLcl target"))
        self.fixture.write(body + "\n", text, text)
        self.assert_refused("no session identity")

    def test_the_expected_user_must_equal_the_schema(self) -> None:
        self.good()
        with self.assertRaises(OrdsExportError) as raised:
            self.fixture.verify(expected_user="DEPLOYER")
        self.assertIn("needs the schema owner", str(raised.exception))

    def test_sqlcl_errors_are_refused_although_sqlcl_exited_zero(self) -> None:
        text = export_text()
        for message in (
            "ORA-00942: table or view does not exist",
            "SP2-0310: unable to open file",
            "Error: java.sql.SQLException: ORA-01017: invalid credentials",
            "Could not find ORDS installed in the current Database.",
            "Failed to execute the ORDS export function. Please ensure you have latest ORDS version installed in your database.",
            "Export failed due to: something",
            "Could not find schema named REST_API. Please ensure you have entered the correct name and that your schema is REST enabled.",
            "NOT CONNECTED.",
        ):
            with self.subTest(message=message):
                self.fixture.write(transcript(extra=message), text, text)
                with self.assertRaises(OrdsExportError):
                    self.fixture.verify()

    def test_an_unsupported_ords_release_is_named_as_such(self) -> None:
        text = export_text()
        message = "Failed to execute the ORDS export function. Please ensure you have latest ORDS version installed in your database."
        self.fixture.write(transcript(extra=message), text, text)
        self.assert_refused("unsupported ORDS release")

    def test_a_sqlcl_message_in_place_of_the_script_is_refused(self) -> None:
        message = "Could not find ORDS installed in the current Database.\n"
        self.fixture.write(transcript(), message, message)
        self.assert_refused("ORDS is not installed")

    def test_handler_source_may_mention_errors_tokens_and_secrets(self) -> None:
        source = "-- ORA-00001: handled below'';  p_token => :token, secret client oauth ORDS.CREATE_ROLE"
        text = export_text(handler_source=source.replace("ORDS.CREATE_ROLE", "x"))
        # An export echoed to the screen while spooling holds the same application code.
        self.fixture.write(transcript(extra=text.replace("\r", "")), text, text)
        self.fixture.verify()

    def test_a_missing_export_file_is_refused(self) -> None:
        self.fixture.write(transcript(), None, export_text())
        self.assert_refused("export file is missing or empty")

    def test_an_empty_export_file_is_refused(self) -> None:
        self.fixture.write(transcript(), "", export_text())
        self.assert_refused("export file is missing or empty")

    def test_a_missing_second_export_is_refused(self) -> None:
        self.fixture.write(transcript(), export_text(), None)
        self.assert_refused("second export file is missing or empty")

    def test_a_truncated_export_is_refused_at_every_cut_point(self) -> None:
        full = export_text()
        for cut in (len(full) // 4, len(full) // 2, len(full) - 12, len(full) - 3):
            with self.subTest(cut=cut):
                self.fixture.write(transcript(), full[:cut], full)
                with self.assertRaises(OrdsExportError):
                    self.fixture.verify()
                self.fixture.write(transcript(), full, full[:cut])
                with self.assertRaises(OrdsExportError):
                    self.fixture.verify()

    def test_an_export_of_another_schema_is_refused(self) -> None:
        text = export_text(schema="OTHER")
        self.fixture.write(transcript(), text, text)
        self.assert_refused("names schema OTHER, not REST_API")

    def test_an_export_without_the_generator_header_is_refused(self) -> None:
        text = "BEGIN\n  ORDS.ENABLE_SCHEMA(p_enabled => TRUE);\nCOMMIT;\nEND;\n"
        self.fixture.write(transcript(), text, text)
        self.assert_refused("does not start with the generator header")

    def test_every_exact_entity_must_match_the_dictionary(self) -> None:
        for key, expected_name in (
            ("modules", "DEFINE_MODULE"), ("templates", "DEFINE_TEMPLATE"), ("handlers", "DEFINE_HANDLER"), ("parameters", "DEFINE_PARAMETER"),
        ):
            with self.subTest(entity=key):
                short = export_text(counts={key: COUNTS[key] - 1})
                self.fixture.write(transcript(), short, short)
                with self.assertRaises(OrdsExportError) as raised:
                    self.fixture.verify()
                self.assertIn(expected_name, str(raised.exception))

    def test_ords_built_in_roles_and_privileges_may_be_missing_from_the_export_but_never_extra(self) -> None:
        # A live ORDS lists its shipped roles and privileges in the dictionary and exports only the schema's own.
        fewer = export_text(counts={"roles": 0, "privileges": 0})
        self.fixture.write(transcript(), fewer, fewer)
        self.fixture.verify()
        for key, call in (("roles", "CREATE_ROLE"), ("privileges", "DEFINE_PRIVILEGE")):
            with self.subTest(entity=key):
                extra = export_text(counts={key: COUNTS[key] + 1})
                self.fixture.write(transcript(), extra, extra)
                with self.assertRaises(OrdsExportError) as raised:
                    self.fixture.verify()
                self.assertIn(call, str(raised.exception))

    def test_both_script_endings_are_complete(self) -> None:
        for ending in ("COMMIT;\n\nEND;\n", "COMMIT;\nEXCEPTION\n  WHEN OTHERS THEN\n    ROLLBACK;\n    RAISE;\n\nEND;\n/\n"):
            with self.subTest(ending=ending[:20]):
                text = export_text()
                text = text[: text.index("COMMIT;")] + ending
                self.fixture.write(transcript(), text, text)
                self.fixture.verify()

    def test_an_auto_rest_object_missing_from_the_export_is_refused(self) -> None:
        text = export_text()
        before = inventory("before", enabled_objects=2)
        self.fixture.write(transcript(before=before, after=before.replace(":before:", ":after:")), text, text)
        self.assert_refused("ENABLE_OBJECT")

    def test_metadata_changing_between_the_inventories_is_refused(self) -> None:
        text = export_text()
        self.fixture.write(transcript(after=inventory("after", handlers=4)), text, text)
        self.assert_refused("changed while it was exported")

    def test_metadata_changing_between_the_two_exports_is_refused(self) -> None:
        self.fixture.write(transcript(), export_text(), export_text(handler_source="null; -- edited"))
        self.assert_refused("two consecutive exports differ")

    def test_an_unavailable_or_malformed_inventory_never_means_an_empty_schema(self) -> None:
        text = export_text()
        full = transcript()
        cases = {
            "no inventory": "\n".join(line for line in full.splitlines() if "ORDS_INVENTORY" not in line) + "\n",
            "no after inventory": "\n".join(line for line in full.splitlines() if "ORDS_INVENTORY:after" not in line) + "\n",
            "duplicated": full + inventory("before") + "\n",
            "malformed": full.replace("clients=0", "clients=x"),
            "missing key": full.replace(",clients=0", ""),
        }
        for label, body in cases.items():
            with self.subTest(case=label):
                self.fixture.write(body, text, text)
                with self.assertRaises(OrdsExportError) as raised:
                    self.fixture.verify()
                self.assertTrue(any(word in str(raised.exception) for word in ("inventory", "ORDS_INVENTORY")), str(raised.exception))

    def test_an_export_that_did_not_reach_its_end_marker_is_refused(self) -> None:
        text = export_text()
        body = "\n".join(line for line in transcript().splitlines() if "ORDS_EXPORT_COMPLETE" not in line) + "\n"
        self.fixture.write(body, text, text)
        self.assert_refused("did not run to the end")

    def test_a_missing_access_check_marker_is_refused(self) -> None:
        text = export_text()
        body = "\n".join(line for line in transcript().splitlines() if "ORDS_ACCESS_VERIFIED" not in line) + "\n"
        self.fixture.write(body, text, text)
        self.assert_refused("ORDS_ACCESS_VERIFIED")

    def test_a_schema_that_owns_oauth_clients_is_refused(self) -> None:
        text = export_text()
        before = inventory("before", clients=1)
        self.fixture.write(transcript(before=before, after=before.replace(":before:", ":after:")), text, text)
        self.assert_refused("OAuth client")

    def test_oauth_material_in_an_export_is_refused(self) -> None:
        text = export_text().replace("COMMIT;", "  ORDS_METADATA.OAUTH.IMPORT_CLIENT(\n    p_name => 'c',\n    p_client_id => 'x');\nCOMMIT;")
        self.fixture.write(transcript(), text, text)
        self.assert_refused("OAuth client or secret material")
        text = export_text().replace("COMMIT;", "  ORDS.CREATE_CLIENT(p_name => 'c');\nCOMMIT;")
        self.fixture.write(transcript(), text, text)
        self.assert_refused("OAuth client or secret material")

    def test_nothing_is_rewritten_when_verification_fails(self) -> None:
        text = export_text(newline="\r\n")
        self.fixture.write(transcript(after=inventory("after", handlers=4)), text, text)
        with self.assertRaises(OrdsExportError):
            self.fixture.verify()
        self.assertEqual(text.encode(), self.fixture.export.read_bytes())
        self.assertTrue(self.fixture.second.exists())


# Application source a handler may legitimately store in its string literal.
STORED_SOURCE = "\n".join([
    "x",
    "ORDS.DEFINE_MODULE(",
    "  ORDS.DEFINE_HANDLER(",
    "ORDS_METADATA.OAUTH.IMPORT_CLIENT(",
    "p_client_id => ''x''",
    "COMMIT;",
    "END;",
    "-- ORA-00942: a stored comment, not an error",
    "it''s a quoted word",
    "/* ORDS.DEFINE_TEMPLATE( */",
])


class OrdsExportLiteralAwareTests(unittest.TestCase):
    """Counts, OAuth detection and the transcript scan read code, never stored handler source."""

    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.fixture = Fixture(Path(self.temporary.name))

    def assert_refused(self, fragment: str) -> None:
        with self.assertRaises(OrdsExportError) as raised:
            self.fixture.verify()
        self.assertIn(fragment, str(raised.exception))

    def test_stored_source_that_looks_like_calls_or_oauth_is_neither_counted_nor_refused(self) -> None:
        text = export_text(handler_source=STORED_SOURCE)
        self.fixture.write(transcript(), text, text)
        self.fixture.verify()
        self.assertIn("ORDS_METADATA.OAUTH.IMPORT_CLIENT(", self.fixture.export.read_text(encoding="utf-8"), "the source is kept as exported")

    def test_a_missing_real_module_definition_is_not_made_up_by_stored_source(self) -> None:
        # The dictionary lists one module; the only DEFINE_MODULE text left is inside a handler's source.
        text = export_text(counts={"modules": 0}, handler_source="x\nORDS.DEFINE_MODULE(\n")
        self.assertIn("\nORDS.DEFINE_MODULE(\n", text)
        self.fixture.write(transcript(), text, text)
        self.assert_refused("the dictionary lists 1 modules but the export has 0 DEFINE_MODULE")

    def test_a_real_call_commented_out_is_not_counted(self) -> None:
        text = export_text().replace("  ORDS.DEFINE_MODULE(", "  -- ORDS.DEFINE_MODULE(", 1)
        self.fixture.write(transcript(), text, text)
        self.assert_refused("DEFINE_MODULE")
        text = export_text().replace("  ORDS.DEFINE_MODULE(", "  /*\n  ORDS.DEFINE_MODULE(\n  */", 1)
        self.fixture.write(transcript(), text, text)
        self.assert_refused("DEFINE_MODULE")

    def test_comments_that_look_like_calls_do_not_inflate_the_counts(self) -> None:
        text = export_text().replace(
            "  ORDS.FINALIZE_IMPORT(", "  -- ORDS.DEFINE_MODULE(\n  /* ORDS.DEFINE_TEMPLATE(\n  ORDS.DEFINE_HANDLER( */\n  ORDS.FINALIZE_IMPORT(", 1
        )
        self.fixture.write(transcript(), text, text)
        self.fixture.verify()

    def test_a_real_oauth_call_is_still_refused_next_to_stored_source(self) -> None:
        text = export_text(handler_source=STORED_SOURCE).replace("COMMIT;\nEXCEPTION", "  ORDS.CREATE_CLIENT(p_name => 'c');\nCOMMIT;\nEXCEPTION", 1)
        self.fixture.write(transcript(), text, text)
        self.assert_refused("OAuth client or secret material")

    def test_a_truncation_inside_a_literal_cannot_look_complete(self) -> None:
        text = export_text(handler_source="x'' COMMIT; END;")
        cut = text.index("COMMIT; END;") + len("COMMIT; END;")
        self.fixture.write(transcript(), text[:cut], text)
        self.assert_refused("truncated")

    def test_an_echoed_export_with_internal_commit_end_blocks_and_error_like_comments_is_ignored(self) -> None:
        text = export_text(handler_source=STORED_SOURCE)
        self.fixture.write(transcript(extra=text), text, text)
        self.fixture.verify()

    def test_a_real_sqlcl_error_after_an_echoed_export_is_still_refused(self) -> None:
        text = export_text(handler_source=STORED_SOURCE)
        self.fixture.write(transcript(extra=text + "\nORA-00942: table or view does not exist"), text, text)
        self.assert_refused("SQLcl reported an error")

    def test_an_echoed_export_without_a_real_end_is_not_stripped(self) -> None:
        # No COMMIT; END; outside a literal: the scan stays strict instead of guessing.
        text = export_text(handler_source=STORED_SOURCE)
        truncated = text[: text.index("  ORDS.FINALIZE_IMPORT(")]
        self.fixture.write(transcript(extra=truncated), text, text)
        self.assert_refused("SQLcl reported an error")


class MaskSqlTests(unittest.TestCase):
    def test_comments_and_literal_contents_are_blanked_and_positions_kept(self) -> None:
        text = "a -- note 'x'\nb 'it''s' /* c\nd */ e q'[it's ]' f \"q--r\" g\n"
        masked = ords_export.mask_sql(text)
        self.assertEqual(len(text), len(masked))
        self.assertEqual(text.count("\n"), masked.count("\n"))
        self.assertEqual(["a", "b", "e", "f", "g"], masked.split())

    def test_q_quote_delimiters(self) -> None:
        for quoted in ("q'[a ' b]'", "q'{a ' b}'", "q'(a ' b)'", "q'<a ' b>'", "q'#a ' b#'", "Q'!a ' b!'"):
            with self.subTest(quoted=quoted):
                self.assertEqual(["x", "y"], ords_export.mask_sql(f"x {quoted} y").split())

    def test_an_identifier_ending_in_q_is_not_an_alternative_quote(self) -> None:
        self.assertEqual("seq 'abc'".replace("'abc'", "     "), ords_export.mask_sql("seq 'abc'"))

    def test_an_unterminated_literal_or_comment_is_blanked_to_the_end(self) -> None:
        for text in ("a 'open COMMIT; END;", "a /* open COMMIT; END;", 'a "open COMMIT; END;'):
            with self.subTest(text=text):
                self.assertEqual(["a"], ords_export.mask_sql(text).split())

    def test_strip_echoed_export_finds_the_end_that_is_code(self) -> None:
        body = export_text(handler_source="x\nCOMMIT;\nEND;\nTAILMARK")
        stripped = ords_export.strip_echoed_export(f"before\n{body}\nafter\n")
        self.assertEqual(["before", "after"], stripped.split(), "everything of the export goes, including text after an internal COMMIT; END;")

    def test_strip_echoed_export_removes_every_echoed_export_and_keeps_the_rest(self) -> None:
        body = export_text(handler_source="x\nCOMMIT;\nEND;\nTAILMARK")
        stripped = ords_export.strip_echoed_export(f"one\n{body}\ntwo\n{body}\nthree\n")
        self.assertEqual(["one", "two", "three"], stripped.split())

    def test_strip_echoed_export_leaves_text_without_a_code_level_end_alone(self) -> None:
        text = "before\n-- Generated by ORDS\nBEGIN\n  ORDS.DEFINE_HANDLER(p_source => 'COMMIT; END;');\nafter\n"
        self.assertEqual(text, ords_export.strip_echoed_export(text))

class OrdsExportSupportTests(unittest.TestCase):
    def test_normalize_drops_only_the_header_date_and_blank_edges(self) -> None:
        text = f"\n\n-- Generated by X\n{DATE_LINE}\n--\n\nBEGIN\n  -- Schema: A  Date: keep\nCOMMIT;\n\nEND;\n\n\n"
        self.assertEqual(
            "-- Generated by X\n-- Schema: REST_API\n--\n\nBEGIN\n  -- Schema: A  Date: keep\nCOMMIT;\n\nEND;\n",
            ords_export.normalize(text),
        )

    def test_a_trailing_slash_after_end_is_accepted(self) -> None:
        text = ords_export.normalize(export_text().replace("END;\n", "END;\n/\n"))
        ords_export.check_structure(text, SCHEMA, "export")

    def test_sqlcl_release_requirement(self) -> None:
        self.assertEqual("26.2.2.0", ords_export.check_sqlcl_version("SQLcl: Release 26.2.2.0 Production Build: 26.2.2.233.1901"))
        self.assertEqual("26.1.0.0", ords_export.check_sqlcl_version("SQLcl: Release 26.1.0.0 Production Build: 26.1.0.1"))
        self.assertEqual("27.1", ords_export.check_sqlcl_version("SQLcl: Release 27.1 Production"))
        for text in ("SQLcl: Release 25.4.0.0 Production", "SQLcl: Release 24.3.1.311.0954 Production", "SQLcl: Release 9.9", "nonsense", ""):
            with self.subTest(text=text), self.assertRaises(OrdsExportError):
                ords_export.check_sqlcl_version(text)

    def test_command_line_reports_a_refusal_on_stderr_with_status_two(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            version = Path(temporary) / "version.txt"
            version.write_text("SQLcl: Release 25.1.0.0 Production\n", encoding="utf-8")
            stdout, stderr = io.StringIO(), io.StringIO()
            with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
                status = ords_export.main(["sqlcl-version", str(version)])
            self.assertEqual(2, status)
            self.assertIn("SQLcl 26.1 or newer is required", stderr.getvalue())
            self.assertEqual("", stdout.getvalue())
            version.write_text("SQLcl: Release 26.2.2.0 Production\n", encoding="utf-8")
            with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
                self.assertEqual(0, ords_export.main(["sqlcl-version", str(version)]))
            self.assertIn("SQLcl 26.2.2.0 supports the ORDS export", stdout.getvalue())

    def test_command_line_verify_names_the_schema_when_it_refuses(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            fixture = Fixture(Path(temporary))
            fixture.write(transcript(user="DEPLOYER"), export_text(), export_text())
            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                status = ords_export.main([
                    "verify", "--stage", temporary, "--spool-schema", SPOOL, "--schema", SCHEMA,
                    "--expected-user", SCHEMA, "--transcript", str(fixture.transcript),
                ])
            self.assertEqual(2, status)
            self.assertIn("ORDS export verification failed for REST_API", stderr.getvalue())


if __name__ == "__main__":
    unittest.main()
