-- Generated by ORDS REST Data Services 26.2
-- Schema: REST_API  Date: Tue Sep 01 04:30:31 2026 
--
BEGIN
  ORDS.ENABLE_SCHEMA(p_enabled => TRUE, p_schema => 'REST_API', p_url_mapping_pattern => 'api');
  ORDS.DEFINE_MODULE(p_module_name => 'legacy.api', p_base_path => '/legacy/');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'legacy.api', p_pattern => 'old');
  ORDS.DEFINE_HANDLER(p_module_name => 'legacy.api', p_pattern => 'old', p_method => 'GET', p_source => 'null;');
  ORDS.DEFINE_MODULE(p_module_name => 'current.api', p_base_path => '/current/');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'current.api', p_pattern => 'new');
  ORDS.DEFINE_HANDLER(p_module_name => 'current.api', p_pattern => 'new', p_method => 'GET', p_source => 'null;');
  COMMIT;
END;
/
