#!/usr/bin/env python3
"""Judge and install one schema's ORDS export staged by scripts/ords_export.sql.

SQLcl exits 0 and leaves a non-empty spool file after many failures, so the
wrappers never trust either. This helper decides from the evidence:

* the transcript proves who was connected, that the access checks passed, that
  the export ran to the end, and carries two inventory lines read from the ORDS
  dictionary views (before and after the export);
* the two spool files (the export, and a second export taken after it) must be
  complete, name the right schema, agree with the inventory and with each other;
* nothing that looks like an OAuth client, secret or token may be present.

``verify`` rewrites the staged ``schema.sql`` in its final form (LF line
endings, no export timestamp) and removes the second export. It never touches
the repository; installing the mirror is replace_mirror's job.

``sqlcl-version`` checks the output of ``sql -V`` against the minimum release.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

# The template's own SQLcl baseline (README), and the release whose bundled
# REST command was inspected: its `REST export schema` calls
# ORDS_METADATA.ORDS_EXPORT.EXPORT_SCHEMA with p_include_enable_schema,
# p_include_privs and p_include_oauth all TRUE.
MIN_SQLCL = (26, 1)

# Inventory keys the SQL prints, in order (ords_inventory.sql).
INVENTORY_KEYS = (
    "schemas",
    "enabled",
    "modules",
    "templates",
    "handlers",
    "parameters",
    "roles",
    "privileges",
    "privilege_roles",
    "privilege_modules",
    "privilege_mappings",
    "enabled_objects",
    "clients",
)

# Inventory entity -> (the PL/SQL call the export emits once per entity, whether
# the count must be exact). Checked against a live ORDS 26.2.3 export:
# modules, templates, handlers and parameters are exported one call each, so
# the counts must be equal. The dictionary views also list the roles and
# privileges that ship with ORDS (oracle.dbtools.auth.*.builtin.*, "SQL
# Developer", ...), which an export correctly leaves out, so for those the
# export may hold fewer calls than the dictionary lists but never more. The
# mappings (privilege_roles, privilege_modules, privilege_mappings) are emitted
# inside DEFINE_PRIVILEGE; they are compared before and after the export and
# between the two exports, not counted call by call.
CALL_RULES = (
    ("modules", "DEFINE_MODULE", True),
    ("templates", "DEFINE_TEMPLATE", True),
    ("handlers", "DEFINE_HANDLER", True),
    ("parameters", "DEFINE_PARAMETER", True),
    ("roles", "CREATE_ROLE", False),
    ("privileges", "DEFINE_PRIVILEGE", False),
    ("enabled_objects", "ENABLE_OBJECT", True),
)

# Entities whose presence in the inventory means the schema is not empty. With
# the schema not REST enabled, every one of them must be zero.
CONTENT_KEYS = tuple(key for key in INVENTORY_KEYS if key not in {"schemas", "enabled"})

# Messages SQLcl and its REST command print for a failed export, always with
# exit status 0 (RestMessages.properties of the REST extension), plus the
# generic Oracle and SQLcl error shapes the other wrappers already refuse.
FAILURE_PATTERNS = (
    (re.compile(r"(SP2|TNS|ORA|PLS|SQL)-[0-9]{4,5}:|SQLcl Error:"), "SQLcl reported an error"),
    (re.compile(r"Could not find ORDS installed"), "ORDS is not installed in this database"),
    (re.compile(r"Failed to execute the ORDS export function"), "unsupported ORDS release: its export function is missing or older than this SQLcl expects"),
    (re.compile(r"Export failed"), "SQLcl's REST export failed"),
    (re.compile(r"Could not find \w+ named "), "SQLcl could not find the REST item to export (is the schema REST enabled?)"),
    (re.compile(r"NOT CONNECTED"), "SQLcl was not connected"),
)

# OAuth clients, client secrets and tokens are never exported (README). SQLcl's
# REST export schema includes OAuth clients, so the SQL refuses a schema that
# owns one, and this scan refuses an export that nevertheless carries one. It
# matches the PL/SQL call at the start of a line, never words or arguments
# inside handler source: a handler may legitimately mention "token".
OAUTH_CALL = re.compile(
    r"^[ \t]*(?:ORDS_METADATA\.)?(?:OAUTH|ORDS|ORDS_ADMIN)\.\w*(?:CLIENT|SECRET)\w*[ \t]*\(",
    re.IGNORECASE | re.MULTILINE,
)
# What SQLcl prints in place of a script (a short message) is all there is of
# a spool file that lacks the generator header.
HEAD_CHARACTERS = 600
# An export that SQLcl echoes to the screen while spooling is application code
# (handler source), which may mention anything. Remove it before judging the
# transcript: from the generator header to the closing COMMIT; END;.
ECHOED_EXPORT = re.compile(
    r"^-- Generated by .*?^[ \t]*COMMIT;[ \t]*\n(?:[ \t]*\n)*(?:[ \t]*EXCEPTION\b.*?\bRAISE;[ \t]*\n(?:[ \t]*\n)*)?[ \t]*END;[ \t]*$",
    re.MULTILINE | re.DOTALL,
)
# How a script ends: COMMIT; then END;, with the EXCEPTION handler ORDS 26.x
# writes (ROLLBACK; RAISE;) in between, and optionally a closing slash.
SCRIPT_TAIL = re.compile(
    r"COMMIT;\s*(?:EXCEPTION\s+WHEN\s+OTHERS\s+THEN\s+ROLLBACK;\s*RAISE;\s*)?END;\s*(?:/\s*)?\Z",
    re.IGNORECASE,
)

SPOOL_NAME = "schema.sql"
VERIFIED_EMPTY_MARKER = "-- Verified empty: the schema is not REST enabled and defines no ORDS metadata."


class OrdsExportError(Exception):
    """The export cannot be trusted; nothing may be installed."""


def parse_sqlcl_version(text: str) -> tuple[int, ...]:
    match = re.search(r"Release\s+(\d+(?:\.\d+)+)", text)
    if match is None:
        raise OrdsExportError("could not read the SQLcl release from `sql -V`")
    return tuple(int(part) for part in match.group(1).split("."))


def check_sqlcl_version(text: str) -> str:
    """Return the release text, or raise when it is older than MIN_SQLCL."""
    version = parse_sqlcl_version(text)
    release = ".".join(str(part) for part in version)
    if version[: len(MIN_SQLCL)] < MIN_SQLCL:
        needed = ".".join(str(part) for part in MIN_SQLCL)
        raise OrdsExportError(
            f"SQLcl {release} is not supported for the ORDS export: SQLcl {needed} or newer is required"
        )
    return release


def scan_failures(text: str, source: str) -> None:
    for pattern, meaning in FAILURE_PATTERNS:
        found = pattern.search(text)
        if found is not None:
            raise OrdsExportError(f"{meaning} ({source}: {found.group(0).strip()!r})")


def parse_inventories(transcript: str) -> dict[str, dict[str, int]]:
    """Return {"before": {...}, "after": {...}}; each must appear exactly once."""
    result: dict[str, dict[str, int]] = {}
    for label in ("before", "after"):
        lines = re.findall(rf"(?m)^[ \t]*ORDS_INVENTORY:{label}:(.*?)[ \t]*$", transcript)
        if len(lines) != 1:
            raise OrdsExportError(
                f"the ORDS inventory ({label} the export) was printed {len(lines)} times, not once; "
                "an unavailable inventory is not an empty schema"
            )
        values: dict[str, int] = {}
        for item in lines[0].split(","):
            name, separator, number = item.partition("=")
            if not separator or not number.isdigit():
                raise OrdsExportError(f"the ORDS inventory ({label} the export) is malformed: {lines[0]!r}")
            values[name] = int(number)
        missing = [key for key in INVENTORY_KEYS if key not in values]
        if missing:
            raise OrdsExportError(f"the ORDS inventory ({label} the export) lacks {', '.join(missing)}")
        result[label] = values
    return result


def single_marker(transcript: str, name: str) -> str:
    values = re.findall(rf"(?m)^[ \t]*{name}:(.*?)[ \t]*$", transcript)
    if len(values) != 1:
        raise OrdsExportError(f"{name} was reported {len(values)} times, not once; the export did not run to the end")
    return values[0]


def verify_identity(transcript: str, schema: str, expected_user: str) -> None:
    if schema != expected_user:
        raise OrdsExportError(f"the expected user {expected_user} is not the REST schema {schema}; the ORDS export needs the schema owner")
    users = re.findall(r"session_user=([^,\s]+)", transcript)
    if not users:
        raise OrdsExportError("the transcript has no session identity; the connection was not verified")
    if any(user.upper() != schema for user in users):
        raise OrdsExportError(f"the session user was {users[0]}, not the REST schema owner {schema}")
    if single_marker(transcript, "ORDS_ACCESS_VERIFIED") != schema:
        raise OrdsExportError("the ORDS access check named a different schema")


def normalize(text: str) -> str:
    """The form installed in the mirror: LF endings and no export timestamp.

    The only line rewritten is the generator's "-- Schema: X  Date: ..." header,
    whose date would otherwise change on every export. Everything else is the
    export as SQLcl produced it.
    """
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    lines = text.split("\n")
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    for index, line in enumerate(lines):
        match = re.match(r"^(-- Schema: \S+)[ \t]+Date:.*$", line)
        if match is not None:
            lines[index] = match.group(1)
            break
    return "\n".join(lines) + "\n" if lines else ""


def check_structure(text: str, schema: str, label: str) -> None:
    lines = text.split("\n")
    if not text.strip() or not lines[0].startswith("-- Generated by "):
        raise OrdsExportError(f"the {label} is not an ORDS export script (it does not start with the generator header)")
    header = []
    for line in lines:
        if not line.startswith("--"):
            break
        header.append(line)
    named = [match.group(1) for line in header if (match := re.match(r"^-- Schema: (\S+)", line))]
    if not named or named[0].upper() != schema:
        raise OrdsExportError(f"the {label} names schema {named[0] if named else 'none'}, not {schema}")
    if SCRIPT_TAIL.search(text) is None:
        raise OrdsExportError(f"the {label} is truncated: it does not end with COMMIT; and END;")
    if not re.search(r"(?im)^[ \t]*ORDS(?:_ADMIN)?\.ENABLE_SCHEMA\s*\(", text):
        raise OrdsExportError(f"the {label} has no ORDS.ENABLE_SCHEMA call")


def count_calls(text: str, name: str) -> int:
    return len(re.findall(rf"(?im)^[ \t]*ORDS(?:_ADMIN)?\.{name}[ \t]*\(", text))


def check_no_oauth(text: str, label: str) -> None:
    found = OAUTH_CALL.search(text)
    if found is not None:
        raise OrdsExportError(
            f"the {label} contains OAuth client or secret material ({found.group(0).strip()!r}); this template exports none"
        )


def check_counts(text: str, inventory: dict[str, int]) -> None:
    for key, call, exact in CALL_RULES:
        found = count_calls(text, call)
        listed = inventory[key]
        name = key.replace("_", " ")
        if exact and found != listed:
            raise OrdsExportError(
                f"the export is incomplete or inconsistent: the dictionary lists {listed} {name} but the export has {found} {call} call(s)"
            )
        if not exact and found > listed:
            raise OrdsExportError(
                f"the export is inconsistent: it has {found} {call} call(s) but the dictionary lists only {listed} {name}"
            )


def describe(inventory: dict[str, int]) -> str:
    return ", ".join(f"{key.replace('_', ' ')}={inventory[key]}" for key in CONTENT_KEYS if key != "clients")


def verify(stage: Path, spool_schema: str, schema: str, expected_user: str, transcript_path: Path) -> str:
    """Verify one schema's staged export, rewrite it in final form, return a summary."""
    transcript = transcript_path.read_text(encoding="utf-8", errors="replace")
    scan_failures(ECHOED_EXPORT.sub("", transcript), "SQLcl transcript")
    verify_identity(transcript, schema, expected_user)
    inventories = parse_inventories(transcript)
    before, after = inventories["before"], inventories["after"]
    if before != after:
        raise OrdsExportError(
            f"the ORDS metadata of {schema} changed while it was exported (before: {describe(before)}, after: {describe(after)})"
        )
    if before["clients"] != 0:
        raise OrdsExportError(f"{schema} owns {before['clients']} OAuth client(s); this template exports none")
    mode = single_marker(transcript, "ORDS_EXPORT_MODE")
    if single_marker(transcript, "ORDS_EXPORT_COMPLETE") != schema:
        raise OrdsExportError("the export completion marker named a different schema")

    ords_dir = stage / "database" / spool_schema / "ords"
    verify_dir = stage / "verify" / spool_schema
    target = ords_dir / SPOOL_NAME
    if mode == "skipped-not-enabled":
        if before["enabled"] != 0 or any(before[key] for key in CONTENT_KEYS):
            raise OrdsExportError(
                f"{schema} is not REST enabled yet the dictionary lists ORDS metadata ({describe(before)}); the inventory is inconsistent"
            )
        ords_dir.mkdir(parents=True, exist_ok=True)
        target.write_text(f"-- ORDS metadata export for schema {schema}\n{VERIFIED_EMPTY_MARKER}\n", encoding="utf-8", newline="\n")
        shutil.rmtree(verify_dir, ignore_errors=True)
        return f"ORDS export verified for {schema}: verified empty (the schema is not REST enabled and defines no ORDS metadata)"
    if mode != "run":
        raise OrdsExportError(f"unknown export mode {mode!r}")
    if before["enabled"] < 1:
        raise OrdsExportError(f"{schema} was exported although the dictionary does not list it as REST enabled")

    exports = {}
    for label, path in (("export", target), ("second export", verify_dir / SPOOL_NAME)):
        if not path.is_file() or path.stat().st_size == 0:
            raise OrdsExportError(f"the {label} file is missing or empty")
        raw = path.read_text(encoding="utf-8", errors="replace")
        normalized = normalize(raw)
        if not normalized.startswith("-- Generated by "):
            # Not a script at all: name what SQLcl printed in its place.
            scan_failures(raw[:HEAD_CHARACTERS], f"start of the {label}")
        check_structure(normalized, schema, label)
        check_no_oauth(normalized, label)
        exports[label] = normalized
    if exports["export"] != exports["second export"]:
        raise OrdsExportError(f"the ORDS metadata of {schema} changed while it was exported (two consecutive exports differ)")
    check_counts(exports["export"], before)

    target.write_text(exports["export"], encoding="utf-8", newline="\n")
    shutil.rmtree(verify_dir, ignore_errors=True)
    if not any(before[key] for key in CONTENT_KEYS):
        return f"ORDS export verified for {schema}: verified empty (REST enabled, no modules, privileges or roles)"
    return f"ORDS export verified for {schema}: {describe(before)}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    version = commands.add_parser("sqlcl-version", help="check the output of `sql -V`")
    version.add_argument("file", type=Path)
    check = commands.add_parser("verify", help="verify and finalize one staged schema export")
    check.add_argument("--stage", type=Path, required=True)
    check.add_argument("--spool-schema", required=True)
    check.add_argument("--schema", required=True)
    check.add_argument("--expected-user", required=True)
    check.add_argument("--transcript", type=Path, required=True)
    arguments = parser.parse_args(argv)
    try:
        if arguments.command == "sqlcl-version":
            print(f"SQLcl {check_sqlcl_version(arguments.file.read_text(encoding='utf-8', errors='replace'))} supports the ORDS export")
        else:
            print(verify(arguments.stage, arguments.spool_schema, arguments.schema, arguments.expected_user, arguments.transcript))
    except OrdsExportError as error:
        prefix = f"ORDS export verification failed for {arguments.schema}" if arguments.command == "verify" else "ORDS export unavailable"
        print(f"{prefix}: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
