#!/usr/bin/env python3
"""Render APEX background probe CSV output as a Markdown findings matrix."""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path


LOG_HEADER = ["CONTEXT_NAME", "PROBE_NAME", "PROBE_VALUE", "PROBE_ERROR"]
FAULT_HEADER = ["SOURCE", "NAME", "DETAIL"]


def read_csv(path: Path, header: list[str]) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as source:
        rows = list(csv.reader(source))
    if not rows or rows[0] != header:
        raise ValueError(f"unexpected CSV header in {path}: {rows[0] if rows else 'empty file'}")
    records: list[dict[str, str]] = []
    for line_number, row in enumerate(rows[1:], start=2):
        if not row:
            continue
        if len(row) > len(header):
            raise ValueError(f"unexpected CSV field count in {path} at line {line_number}")
        padded = row + [""] * (len(header) - len(row))
        records.append(dict(zip(header, padded, strict=True)))
    return records


def markdown_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def cell(row: dict[str, str]) -> str:
    if row["PROBE_ERROR"]:
        text = f"error: {row['PROBE_ERROR']}"
    else:
        text = row["PROBE_VALUE"] or "<null>"
    return markdown_cell(text)


def render(log: list[dict[str, str]], faults: list[dict[str, str]], apex: str, database: str) -> str:
    contexts: list[str] = []
    probes: list[str] = []
    values: dict[tuple[str, str], str] = {}
    for row in log:
        context = row["CONTEXT_NAME"]
        probe = row["PROBE_NAME"]
        if context not in contexts:
            contexts.append(context)
        if probe not in probes:
            probes.append(probe)
        values[(probe, context)] = cell(row)
    lines = [
        "# APEX background probe findings",
        "",
        f"Observed on APEX {markdown_cell(apex)}, database {markdown_cell(database)}. "
        "Generated by probe/render_findings.py; do not edit by hand. `<null>` means the probe returned NULL; `-` means the context",
        "did not record that probe.",
        "",
        "| Probe | " + " | ".join(markdown_cell(context) for context in contexts) + " |",
        "| --- | " + " | ".join("---" for _ in contexts) + " |",
    ]
    for probe in probes:
        row_values = [values.get((probe, context), "-") for context in contexts]
        lines.append("| " + markdown_cell(probe) + " | " + " | ".join(row_values) + " |")
    lines += ["", "## Faults", ""]
    if faults:
        lines += [
            "- "
            + markdown_cell(fault["SOURCE"])
            + " `"
            + markdown_cell(fault["NAME"]).replace("`", "\\`")
            + "`: "
            + markdown_cell(fault["DETAIL"])
            for fault in faults
        ]
    else:
        lines.append("No faults recorded.")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("log_csv", type=Path)
    parser.add_argument("faults_csv", type=Path)
    parser.add_argument("--apex", required=True)
    parser.add_argument("--database", required=True)
    args = parser.parse_args(argv)
    try:
        log = read_csv(args.log_csv, LOG_HEADER)
        faults = read_csv(args.faults_csv, FAULT_HEADER)
    except (OSError, ValueError) as exc:
        print(f"render error: {exc}", file=sys.stderr)
        return 1
    sys.stdout.write(render(log, faults, args.apex, args.database))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
